'use strict';(function(tandf){var AjaxWidgets={Observe:function(item,data,override){if(item){var observer=Settings.observer;if(observer&&item.useObserver)
observer.observe(item.wrapper);else
AjaxWidgets.Load(item,data,override,Utils.GetWidgetDef(item.key).conf);}},Load:function(item,data,override,conf,append){conf=conf||Utils.GetWidgetDef(item.key);$(item.widget).pbAjax({success:function(html){append?append(item,html):Utils.RenderWidget(item,html);Utils.UpdateWidget(item);if(conf.success)
conf.success(item);item.events.loaded=true;$.event.trigger("AjaxWidgetsLoaded:"+item.key,{widgetItem:item});Utils.Log("Widget [{0}] loaded.".format(item.key));},beforeSend:function(xhr){if(item.events.loading){Utils.Log("Widget [{0}] still loading".format(item.key));xhr.abort();}else if(item.events.loaded&&!override){Utils.Log("Widget [{0}] already loaded".format(item.key));xhr.abort();}else{if(!append)
item.wrapper.innerHTML="";item.events.loading=true;}},error:function(e){Utils.Log("Error loading widget [{0}], cause: {1}".format(item.key,e.statusText));if(conf.error)
conf.error(e)},complete:function(){item.events.loading=false;},url:'/pb/widgets/ajax/graphql/'+conf.url,data:data,});},Init:function(){Settings.widgets.forEach(function(el){if(Settings.widgetDefs[el.key].active()){AjaxWidgets.Observe(el);}else{var widget=el.widget,tab=widget.closest(".tab-pane"),tabLi=tab&&tab.id?document.querySelector('a[href$="'+tab.id+'"]').parentElement:undefined;if(tabLi){hide(tabLi);hide(tab);}
hide(widget);Utils.Log("Widget [{0}] is not active, skipping".format(el.key));}})
function hide(e){e.classList.add("hide-completely")}
$.event.trigger("AjaxWidgetsInit");$.event.trigger("WidgetReinit.layout-tabs");}};var Settings={registered:false,observer:null,widgetDefs:{},widgets:[],conf:{url:"",active:function(){return true},success:null,error:null},RegisterObserver:function(){Utils.Log("Registering Observer");if("IntersectionObserver"in window){this.observer=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){var w=entry.target,item=Utils.GetWidgetItem(w);Utils.Log("loading [{0}] from IntersectionObserver.".format(item.key));observer.unobserve(w);AjaxWidgets.Load(item);}});});Utils.Log("Registering Observer is done");}else
Utils.Log("Registering Observer was unsuccessful, IntersectionObserver is unsupported on this browser");},Register:function(widgets){if(!document.body){Utils.Log("Calling register before document.body is fully loaded.");return;}
if(!this.registered){this.registered=true;setTimeout(function(){Settings.RegisterObserver();Object.keys(widgets).forEach(function(key){Settings.widgetDefs[key]=TandfUtils.extend(widgets[key],Settings.conf);});Utils.CollectAjaxWidgets().forEach(function(wrapper){var key=wrapper.dataset['ajaxWidget'];if(Utils.GetWidgetDef(key)){Settings.widgets.push(Utils.GetMappedWidget(wrapper));Utils.Log("[{0}] is registered.".format(key))}else
Utils.Log("Widget definition not found for [{0}], add the definition to AjaxWidgets.Settings.Register.".format(key))});AjaxWidgets.Init();})}else{Utils.Log("Register is called more than once.");}},Reset:function(){this.registered=false;this.widgetDefs={};this.widgets=[];}};var Utils={GetWidgetDef:function(key){return Settings.widgetDefs[key];},UpdateWidget:function(item){item.widget=document.getElementById(item.id);item.wrapper=item.widget.querySelector(".ajaxWidget");},RenderWidget:function(item,html){$(item.widget).replaceWith(html);},Log:function(message){console.debug("AjaxWidgets:: "+message)},GetMappedWidget:function(wrapper){var widget=wrapper.closest(".widget"),map={id:widget.id,key:wrapper.dataset['ajaxWidget'],useObserver:wrapper.dataset["ajaxObserve"],widget:widget,wrapper:wrapper,events:{loaded:false}},loading=false;Object.defineProperty(map.events,'loading',{get:function(){return loading;},set:function(v){loading=v;var l=map.wrapper.classList,s="loading"+(wrapper.dataset["ajaxSpin"]==='true'&&!map.events.loaded?"-spinner":"");loading?l.add(s):l.remove(s);}});return map;},GetWidgetItem:function(widget){var d=widget.dataset;return Settings.widgets.find(function(e){return e.id===d["ajaxWidgetId"];});},CollectAjaxWidgets:function(){return document.querySelectorAll('.ajaxWidget[data-ajax-widget]');}}
tandf.AjaxWidgets=AjaxWidgets;tandf.AjaxWidgets.Settings=Settings;})(tandf);


(function(tandf){$(function(){var AjaxWidgets=tandf.AjaxWidgets;if(AjaxWidgets){console.debug("Attaching AjaxWidgets event listeners");$(document).on(['ajaxMostReadWidget','ajaxMostRecentWidget','ajaxMostCitedWidget','ajaxOpenAccessWidget','ajaxAtmCRWidget','ajaxCFCRWidget','ajaxCitedByWidget','ajaxAltmetricTopCitedArticlesWidget','gql-publication-list'].map(function(e){return'AjaxWidgetsLoaded:'+e}).join(' '),function(e,data){data=data.widgetItem;if(!data.wrapper.innerText){data.widget.classList.add("hide-completely")
return;}
if(!data.widget.closest('.collapsed-view'))
cardsContainer(data.widget);data.widget.querySelector('.paginationLinkContainer')&&data.widget.querySelectorAll('a[data-start-page]').forEach(function(l){l.addEventListener("click",function(e){e.preventDefault();AjaxWidgets.Load(data,{"startPage":l.dataset["startPage"]},true)})})
document.dispatchEvent(new CustomEvent('attach-behaviour'));});$(document).on("AjaxWidgetsLoaded:literatumArticleMetricsWidget AjaxWidgetsLoaded:ajaxMostRecentWidget"+" AjaxWidgetsLoaded:ajaxMostReadWidget AjaxWidgetsLoaded:ajaxMostCitedWidget"+" AjaxWidgetsLoaded:ajaxOpenAccessWidget AjaxWidgetsLoaded:ajaxAtmCRWidget AjaxWidgetsLoaded:ajaxCFCRWidget"+" AjaxWidgetsLoaded:ajaxCitedByWidget AjaxWidgetsLoaded:ajaxAltmetricTopCitedArticlesWidget AjaxWidgetsLoaded:gql-publication-list",function(e,data){var Altmetric=tandf.Altmetric;if(Altmetric){var widget=data.widgetItem.widget;if(widget.querySelector('.compactView')){load(".altmetric-score .value");}else if(widget.querySelector('.metrics-badge')){load(".metrics-badge");}}
function load(selector){var observer=Altmetric.Settings.observer;widget.querySelectorAll(selector).forEach(function(element){observer?observer.observe(element):Altmetric.Helpers.load(element);});}});$(document).on("AjaxWidgetsInit",function(){selectFirstTabEle();});$(document).on('AjaxWidgetsLoaded:ajaxCFCRWidget',function(e,data){e.preventDefault();data=data.widgetItem;var moreBrn=data.widget.querySelector('.collapsed-view--view-more');if(moreBrn){moreBrn.onclick=function(){if(!data.moreLoaded){AjaxWidgets.Load(data,{"viewMore":"true"},true,null,function(e,moreData){$(data.widget).find('.article-card:first-child').parent().append($(moreData).find('.article-card').addClass('more'));data.moreLoaded=true;})}else{$(data.widget).find('.more').toggleClass('hide-completely');}
$(moreBrn).text($(moreBrn).text()==="View more"?"View fewer":"View more");return false;}}})}});})(tandf);


tandf.AjaxWidgets.Settings.Register({"ajaxOpenAccessWidget":{url:"topContentView/ajaxOpenAccessController"},'ajaxMostCitedWidget':{url:'topContentView/ajaxMostCitedController'},'ajaxMostRecentWidget':{url:'topContentView/ajaxMostRecentController'},'ajaxMostReadWidget':{url:'topContentView/ajaxMostReadController'},'ajaxAtmCRWidget':{url:"topContentView/ajaxAtmCRController"},'ajaxCFCRWidget':{url:"ajaxCFCRController",active:function(){return tandfData["search"]["cbRec"]>0}},'gql-content-navigation':{active:function(){return!tandfData["identity"]["isSpv"];},},'literatumArticleMetricsWidget':{url:'altmetric'},'ajaxCitedByWidget':{url:'ajaxCitedByController'},'specialIssuesWidget':{url:'topContentView/specialIssuesController'},'ajaxAltmetricTopCitedArticlesWidget':{url:'ajaxAltmetricTopCitedArticlesController'},'gql-publication-list':{url:'pubList'}});

