
$(function(e){searchBar_journalsInTopNavigation();handleBurgerMenuState();function hideActiveListIfNeeded(){$('li[data-name="journals__browse-subject"] div button').on('click',function(){var isActive=$(this).hasClass('active');$('li.has-child').not($(this).closest('li.has-child')).toggleClass('visuallyHidden',!isActive);});$('.browse--item__dropdown').on('click',function(){var isActive=$(this).hasClass('active');$('.journals--item').toggleClass('visuallyHidden',!isActive);$('.navigation--item__dropdown-content-mobile .publish--item').toggleClass('visuallyHidden',!isActive);});}
function toggleOverlayAndScrollLock(buttonClass){$(buttonClass+' .fa.fa-chevron-down').on('transitionstart',function(){var parentButton=$(this).closest(buttonClass);var isExpanded=parentButton.attr('aria-expanded')==='true';if(!isExpanded&&!document.querySelector('.topnav-journals-button').classList.contains('active')){$('.modal-overlay.top-nav').hide();}else{$('.modal-overlay.top-nav').show();}});}
function searchBar_journalsInTopNavigation(){toggleOverlayAndScrollLock('.topnav-journals-button');toggleOverlayAndScrollLock('.topnav-search-button');window.addEventListener('scroll',function(){if(document.querySelector('.top-navigation')){if(!(document.querySelector('.search-home.navigation--item__dropdown-content')).classList.contains('hidden')){$('.search--item__dropdown.active').click();}
if(!(document.querySelector('.navigation--item__dropdown-content.journals__desktopNavItem')).classList.contains('hidden')&&!isElementInViewport(document.activeElement)){$('.journals--item__dropdown.active').click();}}});}
function isElementInViewport(e){var rect=e.getBoundingClientRect();return rect.bottom>0&&rect.top<window.innerHeight;}
function adjustBurgerMenu(){var respWgt=document.querySelector('.top-nav-resp');var container=document.querySelector('.navigation--item__dropdown-content-mobile');var top=(respWgt.offsetHeight+respWgt.getBoundingClientRect().top)+"px";container.style.top=top;container.style.height='calc(100% - '+top+')';}
function setupDropdownHeightAdjustment(){document.querySelectorAll('.header_burger-menu .journals--item > div button[data-behaviour="toggle-more"]').forEach(function(button){button.addEventListener('click',function(){var container=this.nextElementSibling;if(container&&container.matches('[data-more]')){setTimeout(function(){var ul=container.querySelector('ul');if(ul){var height=ul.offsetHeight+"px";container.style.setProperty('--before-height',height);}},100);}});});}
function hideQuickSearchOnScroll(){$('.navigation--item__dropdown-content-mobile').on('scroll',function(){if($(window).width()<1024){$('.quickSearchAutocomplete').hide();}});}
function handleBurgerMenuState(){var burger_menu=document.querySelector('.header_burger-menu');if(burger_menu){setupDropdownHeightAdjustment();hideQuickSearchOnScroll();hideActiveListIfNeeded();window.addEventListener('resize',function(){adjustBurgerMenu();setupDropdownHeightAdjustment();});$('.burger-menu-button').on('click keydown',function(e){if(e.keyCode===13||e.keyCode===undefined){var bodyClassList=document.body.classList;if(!this.classList.contains('active')){bodyClassList.add('scroll-lock_burger-menu');adjustBurgerMenu();}else{bodyClassList.remove('scroll-lock_burger-menu');}
if($('button.loginBar').attr('aria-expanded')==='true'){$('.loginBar').click();}}});document.querySelector('.header_burger-menu').addEventListener("keydown",function(e){if(this.querySelector('.burger-menu-button').getAttribute('aria-expanded')==='true'){var firstFocusable=$(this).find(':focusable').first();if(e.key==="Tab"){if(e.shiftKey){if($(e.target).is(firstFocusable)){e.preventDefault();$(this).find(':focusable').last().focus();}}else{if($(e.target).is($(this).find(':focusable').last())){e.preventDefault();firstFocusable.focus();}}}}},true);}}});

'use strict';(function(tandf){var behaviours=new Map();var Binder={create:function(name,listener,init){behaviours.set(name,listener);if(init)
init();},_call:function(name,originalEvent){var listener=behaviours.get(name);if(listener){listener.call(this,originalEvent,Binder._buildCallbacks(this));}},_buildCallbacks:function(element){var callback=element.dataset['behaviourCallback'],callbackTarget=element.dataset['behaviourCallbackTarget'],calls=[];if(callback&&callbackTarget){var callTargets=collectCallbacksTargets(callbackTarget);collectCallbacks(callback).forEach(function(c,index){calls.push(function(){Binder._callbacks[c](callTargets[index]);})})
return calls;}
function collectCallbacks(callback){if(callback.startsWith("[")&&callback.endsWith("]")){return callback.substring(1,callback.length-1).split(",");}
return[callback];}
function collectCallbacksTargets(callbackTarget){return collectCallbacks(callbackTarget);}},_callbacks:{'click':function(callbackTarget){document.querySelector(callbackTarget).click();},'expand':function(callbackTarget){var element=document.querySelector(callbackTarget);if(element.getAttribute('aria-expanded')==='false'){element.click();}},'focus':function(callbackTarget){var element=document.querySelector(callbackTarget);element.setAttribute('tabindex','0');element.focus();if(element.localName!=='a'&&element.localName!=='button'){element.setAttribute('tabindex','-1')}}}}
Binder.create('toggle-more',function(event){var wrapper=this.closest('[data-more-wrapper]');if(this.hasAttribute('data-only-one')){wrapper.querySelector('[data-more]').classList.toggle('hidden');}else{wrapper.querySelectorAll('[data-more]').forEach(function(element){element.classList.toggle('hidden');});}
this.classList.toggle('active');this.setAttribute('aria-expanded',this.getAttribute('aria-expanded')==='true'?'false':'true');})
Binder.create('toggle-dropdown',function(event){var $this=this;var expanded=document.querySelector("[data-behaviour='toggle-dropdown'][aria-expanded='true']");if(expanded&&expanded!==$this){Binder._call.call(expanded,'close-dropdown',event)}
Binder._call.call($this,$this.getAttribute('aria-expanded')==='true'?'close-dropdown':'expand-dropdown',event)},function(){document.addEventListener('keydown',function(event){if(event.code==='Escape'){var activeElement=document.querySelector("[data-behaviour='toggle-dropdown'][aria-expanded='true']");if(activeElement){Binder._call.call(activeElement,'close-dropdown',event)}}})
document.addEventListener('click',function(event){event.stopPropagation();var closestBinder=event.target.closest('[data-dropdown-wrapper]');if(!closestBinder){document.dispatchEvent(new KeyboardEvent('keydown',{code:'Escape'}));}})})
Binder.create('expand-dropdown',function(event){this.parentElement.querySelector('[data-dropdown-content]').classList.remove('hidden')
this.classList.add('active');this.setAttribute('aria-expanded','true');this.focus();})
Binder.create('close-dropdown',function(event){var activeElement=this.closest("[data-dropdown-wrapper]").querySelector("[data-behaviour='toggle-dropdown'][aria-expanded='true']");if(activeElement){activeElement.parentElement.querySelector('[data-dropdown-content]').classList.add('hidden');activeElement.classList.remove('active');activeElement.setAttribute('aria-expanded','false');activeElement.focus();}})
Binder.create("toggle-mark-all",function(event){var $this=this,container=$this.closest("[data-markable-container]");container.querySelectorAll("[data-markable] input[type='checkbox']").forEach(function(input){input.checked=$this.checked;})})
Binder.create("show-popup",function(event){tandf.TFViewer.showViewer(event.currentTarget);})
Binder.create("tooltip",function(event){this.closest("[data-tooltip-wrapper]").querySelector('[data-tooltip]').classList.toggle('active');},function(event){document.addEventListener('click',function(event){var closest=event.target.closest('[data-tooltip-wrapper]');if(!closest){document.querySelectorAll('[data-tooltip].active').forEach(function(element){element.classList.remove('active');})}})})
Binder.create("toggle-ref",function(event){var $this=this,overlayClassList=document.querySelector("#ref-overlay").classList;if(!($this.hasAttribute("data-behaviour-toggled")||!overlayClassList.contains('active'))){Binder._call.call($this,'close-ref',event);Binder._call.call($this,'show-ref',event);}else{Binder._call.call($this,overlayClassList.contains('active')?'close-ref':'show-ref',event);}},function(){if(document.querySelectorAll('[data-behaviour="toggle-ref"],[data-behaviour="show-popup"]').length>0){var frag=document.createDocumentFragment();frag.appendChild(new DOMParser().parseFromString('<div id="ref-overlay" tabindex="0" role="dialog" aria-label="reference"><div id="ref-overlay-in" class="rs_skip"><span class="ref-icon"></span><button class="ref-close" tabIndex="0" data-behaviour="close-ref" aria-label="close reference popup"><span aria-hidden="true">×</span></button><div class="content"></div><a href="#" class="frontnotes" data-behaviour="scroll" data-behaviour-ref="#inline_frontnotes" data-behaviour-callback="true">View all notes</a></div></div>',"text/html").body.firstElementChild);if(!document.getElementById("inline_frontnotes")){frag.querySelector(".frontnotes").classList.add("hidden");}
document.body.appendChild(frag);}});Binder.create('scroll',function(event,callbacks){var $this=this,target=$this.dataset['behaviourRef'];if(target){TandfUtils.animate(target,callbacks);}},function(){var initialHash=tandf.initialHash;if(initialHash){var element=document.querySelector(initialHash),ref=document.querySelector("[data-behaviour-ref='"+initialHash+"']");if(ref){Binder._call.call(ref,'scroll');}else if(element){element.scrollIntoView('smooth');}
history.replaceState(null,null,initialHash);}});Binder.create('show-ref',function(event){var $this=this,span=document.querySelector("#ref-overlay"),content=span.querySelector(".content");content.innerHTML=$this.dataset['rid'].split(' ').map(function(id){var ref=document.getElementById(id);if(tandf.getFTR)
tandf.getFTR.load(ref.querySelector('.getFTR__placeholder'));if(ref.querySelector('.getFTR__doiUpdates-wrapper a')){var clone=ref.cloneNode(true);var wrapperLink=clone.querySelector('.getFTR__doiUpdates-wrapper a');if(wrapperLink){wrapperLink.removeAttribute('aria-describedby');var tooltip=clone.querySelector('.getFTR__doiUpdates-tooltip');if(tooltip){tooltip.remove();return clone.innerHTML;}}}
return ref?ref.innerHTML:"";}).reduce(function(accumulator,builder){return accumulator+builder;},"");var dataMathMl=content.querySelectorAll(".NLM_disp-formula");if(dataMathMl.length>0){dataMathMl.forEach(function(element){var converted=element.querySelector('[data-mathml]');if(converted){element.innerHTML=converted.dataset['mathml'];}})
MathJax.startup.promise.then(function(){return MathJax.typesetPromise([content]);}).catch(function(err){console.log('Typesetting failed: '+err.message);});}
document.dispatchEvent(new CustomEvent('attach-behaviour'));$this.setAttribute("data-behaviour-toggled","true");span.setAttribute("data-ref-type",$this.getAttribute("data-ref-type"));span.querySelector(".ref-close").setAttribute("aria-label","close "+$this.dataset['label']+" popup");span.classList.add("active");TandfUtils.restrictFocusToPopup(span);})
Binder.create('close-ref',function(event){var span=document.querySelector("#ref-overlay"),trigger=document.querySelector('[data-behaviour-toggled]');span.classList.remove("active");span.removeAttribute("data-ref-type");trigger.removeAttribute("data-behaviour-toggled");trigger.focus({preventScroll:true});})
Binder.create('open-modal',function(event){var trigger=this,callback=trigger.getAttribute('data-modal-proxy-trigger').split('.');var context=window;for(var i=0;i<callback.length;i++){context=context[callback[i]];if(!context){console.error(callback[i]+" is not a valid function or object");return;}}
if(typeof context==='function'){if(trigger.getAttribute('data-behaviour-proxy')==='true'){benefitsModalProxy.call(trigger,context);}else{context.call(trigger);}}else{console.error(callback+" is not a valid function");}});Binder.create('select-input',function(){var input=document.querySelector(this.dataset['input-selector']);if(input){input.checked=true;}});function register(){document.querySelectorAll("[data-behaviour]:not([data-registered]),[data-behaviour][data-behaviour-force-reload]").forEach(function(e){_registerElement(e)});}
function _registerElement(element){var name=element.dataset['behaviour'],type=element.getAttribute("type"),force=element.dataset['behaviourForceReload'],eventType=element.dataset['behaviourEventType']||'click';if(name){var listener=behaviours.get(name);if(listener){if(force){element.removeEventListener(eventType,_evtListener);}
element.addEventListener(eventType,_evtListener);}
element.setAttribute("data-registered","")}
function _evtListener(evt){var element=evt.currentTarget;if(!(element instanceof HTMLInputElement&&type==='checkbox')){evt.preventDefault();}
listener.call(this,evt,Binder._buildCallbacks(element));}}
$(register);document.addEventListener('attach-behaviour',register);tandf.Binder=Binder;})(tandf);


(function(tandf){if(tandf&&!("TFViewer"in tandf)&&"tfviewerdata"in tandf){var viewer='<div id="viewer" class="{0}"><div class="navigator"><button class="prev" title="Previous {1}"><i aria-hidden="true" class="fa fa-angle-left"></i></button><button class="next" title="Next {1}"><i aria-hidden="true" class="fa fa-angle-right"></i></button></div><div class="header"></div><div class="viewer-canvas"><div class="count"></div><div class="content"></div><div class="download-options"></div></div></div>',downloadOptions='<a class="download-btn" href="/action/downloadTable?id={0}&doi={1}&downloadType=CSV" role="button">Download CSV</a>',count='<h3>{0} <span class="index">{1}</span> of {2}</h3>',parser=new DOMParser(),data=tandf.tfviewerdata;function bind(element,selector,content){element.querySelector(selector).innerHTML+=content;}
function findElement(element){return element?document.querySelector('[data-id="'+element.id+'"]'):undefined;}
tandf.TFViewer={initViewer:function(wrapper,nextElement,prevElement,id,ariaPart){var $this=this,modal=new Modal({name:"viewer-"+id,content:wrapper,padding:5,top:100,maxWidth:1300,id:id,closeButtonA11yAttributes:{'aria-label':'Close '+ariaPart+' Viewer'}});modal.open();var nextNav=modal.getElement('.next'),prevNav=modal.getElement('.prev'),hasNext=nextElement!==undefined,hasPrev=prevElement!==undefined
nextNav.classList.toggle("hide",!hasNext);prevNav.classList.toggle("hide",!hasPrev);if(hasNext){nextNav.addEventListener('click',function(){modal.close();$this.showViewer(nextElement);});}
if(hasPrev){prevNav.addEventListener('click',function(){modal.close();$this.showViewer(prevElement)});}
document.dispatchEvent(new CustomEvent('attach-behaviour'));lazyLoad("[data-formula-source]",modal.modal);},showTable:function(element){var wrapper=parser.parseFromString(viewer.format("table-viewer","Table"),"text/html").querySelector('#viewer'),id=element.dataset['id'].split(" ")[0],index=data['table-index-map'][id],table=data.tables[index];bind(wrapper,'.header',data.metadata.header);bind(wrapper,'.content',table.content);bind(wrapper,'.count',count.format("Table",index+1,data.tables.length));if(table.settings.hasCsvFormat){bind(wrapper,'.download-options',downloadOptions.format(id,data.metadata.doi));}
this.initViewer(wrapper.outerHTML,findElement(data.tables[index+1]),findElement(data.tables[index-1]),id,"Table");if(window.applyMathJaxToggleState){window.applyMathJaxToggleState();}},showFigure:function(element){var wrapper=parser.parseFromString(viewer.format("figure-viewer","Figure"),"text/html").querySelector('#viewer'),id=element.dataset['id'].split(" ")[0],index=data['figure-index-map'][id],figure=data.figures[index];bind(wrapper,'.header',data.metadata.header);bind(wrapper,'.content',figure.content);bind(wrapper,'.count',count.format("Figure",index+1,data.figures.length));this.initViewer(wrapper.outerHTML,findElement(data.figures[index+1]),findElement(data.figures[index-1]),id,"Figure");},showViewer:function(element){if(!window.OpenedModal||window.OpenedModal.modalContext.options.id!==element.dataset['id']){var type=element.getAttribute("data-popup-event-type");if(type==='table'){this.showTable(element);}else if(type==="fig"){this.showFigure(element);}}
var rid=element.dataset['rid'];if(rid){tandf.Binder._call.call(element,'toggle-ref',null);}}}}})(tandf);


(function(tandf){var url="/action/CitationEntitlement",updatesUrl="/action/fetchDoiUpdates",elementCount=20,requestBody={"pubDoi":undefined,"associatedCitations":undefined,"requestSource":"FULL_TEXT"},references=document.querySelectorAll(".getFTR"),loadedCount=0,map=new Map();if(!references.length){return;}
requestBody.pubDoi=decodeURIComponent(TandfUtils.parsePageContext().article.value);var intersectionObserver=new IntersectionObserver(function(entries,observer){if(loadedCount>=references.length){intersectionObserver.disconnect();console.log("Disconnect GetFTR observer as all elements were observed");return;}
entries.forEach(function(entry){var pos=entry.target.dataset.pos;if(entry.isIntersecting){map.set(Math.ceil(pos/elementCount),[]);}});unobserveElements();_load();});references.forEach(function(ref,pos){ref.dataset['pos']=(pos+1).toString();intersectionObserver.observe(ref);});function loadOnDemand(element){if(element){var pos=element.dataset.pos,idx=Math.ceil(pos/elementCount);if(!map.has(idx)){map.set(idx,[]);unobserveElements();_load();}}}
function unobserveElements(){references.forEach(function(element){var dataset=element.dataset;var batch=Math.ceil(dataset.pos/elementCount);if(map.has(batch)){map.get(batch).push(dataset.target);intersectionObserver.unobserve(element);}});}
document.addEventListener("DOMContentLoaded",function(){Promise.all([getDois(references,"Reference"),]).then(function(){}).catch(function(err){console.error("Error loading DOIs:",err);});});function _load(){map.forEach(function(value,key){console.log("fetching elements from range "+key+" to "+key*elementCount);loadedCount+=elementCount;load(value);});map.clear();}
function getDois(items,location){if(!items||items.length===0)return Promise.resolve();var dois=Array.prototype.slice.call(items).map(function(element){return element.getAttribute("data-target");}).filter(Boolean);if(dois.length>0){var promises=[];for(var i=0;i<dois.length;i+=100){var chunkDois=dois.slice(i,i+100);promises.push(fetchDoiUpdates(chunkDois,location));}
if(promises.length>0){return getAndHandlePromises(promises);}}
return Promise.resolve();}
function getAndHandlePromises(promises){return Promise.allSettled(promises).then(function(results){results.forEach(function(result,idx){if(result.status==="rejected"){console.error("Chunk "+idx+" failed in getDois:",result.reason);}});});}
function fetchDoiUpdates(dois,location){var body={pubDoi:requestBody.pubDoi,associatedCitations:dois,requestSource:requestBody.requestSource,location:location};return fetch(updatesUrl,{method:"POST",headers:{"Content-Type":"application/json",},body:JSON.stringify(body),}).then(function(response){return response.json();}).then(function(results){results.forEach(function(item,index){getFTRDoiUpdates(item,index);});}).catch(function(error){console.error("Error:",error);});}
function getFTRDoiUpdates(data,index){var toolTipId='toolTip-'+(index+1);var type=data['updateType']==='retraction'?'retraction':'updates';var url=data['url'];var tooltipTitle=data['updateType']==='retraction'?'This document was retracted at '+data['updateDate']:'This document has been updated';var tooltipList=data['reasons'].length?'<b>Reasons:</b><ul class="list">'+data['reasons'].map(function(reason){return'<li>'+reason+'</li>';}).join('')+'</ul>':'';var tooltipHint="Click for further information.";var htmlContent='<div class="getFTR__doiUpdates-wrapper">'+'<a href="'+url+'" class="getFTR__btn getFTR__doiUpdates-btn '+type+'" target="_blank" tabindex="0"  aria-describedby="'+toolTipId+'">'+'<i aria-hidden="true" class="icon icon-warning-triangle '+type+'"></i> '+type+'</a>'+'<div id="'+toolTipId+'" role="tooltip" class="getFTR__doiUpdates-tooltip">'+'<i aria-hidden="true" class="icon icon-warning-triangle '+type+'"></i>'+'<div>'+'<p class="title">'+tooltipTitle+'</p>'+
tooltipList+'<p class="hint">'+tooltipHint+'</p>'+'</div>'+'</div>'+'</div><span></span>';var getFTRContent=document.querySelector('[data-target="'+data['doi']+'"]');if(getFTRContent){getFTRContent.parentElement.insertAdjacentHTML("afterend",htmlContent);}}
function load(associatedCitations){requestBody.associatedCitations=associatedCitations;fetch(url,{method:"POST",body:JSON.stringify(requestBody)}).then(function(value){return value.json();}).then(function(json){json.forEach(function(obj){var doi=obj.doi,entitlement=obj.entitlement,fallback=obj.fallback,entitled,accessType,type,iconPath,tooltip,url;if(entitlement!==undefined){entitled=entitlement.entitled;accessType=entitlement.accessType;type=entitlement.type;if(entitled==='yes'&&(accessType==='open'||accessType==='free'||accessType==='permFree'||accessType==='paid')){iconPath='/templates/jsp/_style2/_tandf/images/full-getftr.png';}else if(entitled==='no'&&type==='av'){iconPath='/templates/jsp/_style2/_tandf/images/alternative-getftr.png';}
tooltip=entitlement.tooltip;url=entitlement.url;}else if(fallback!==undefined){url=fallback.url;}
var a="<li> <a "+"href='"+url+"' "+"target='_blank' "+"class='getFTR__btn"+(tooltip?" getFTR__tooltip' aria-label='"+tooltip+" (view in a new window)"+"' data-tooltip='"+tooltip+"'>":"'aria-label='View (open in a new window)'>")+
(iconPath?"<img src='"+iconPath+"' alt='view'/>":"")+"<span>View</span></a></li>";var targetElement=document.querySelectorAll('[data-target="'+doi+'"]');if(targetElement&&targetElement.length===1){if(!targetElement[0].querySelector("li a.getFTR__btn")){targetElement[0].insertAdjacentHTML("beforeend",a);}}else{targetElement.forEach(function(elm){if(!elm.querySelector("li a.getFTR__btn")){elm.insertAdjacentHTML("beforeend",a);}});}});}).catch(function(reason){console.log(reason);});}
tandf.getFTR={load:loadOnDemand};})(tandf);

'use strict';(function(tandf){var Altmetric={Settings:{registered:false,key:tandfData.altmetric.key,observer:null},Helpers:{registerObserver:function(){var helper=Altmetric.Helpers;if(window.IntersectionObserver){Altmetric.Settings.observer=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){var element=entry.target;observer.unobserve(element);helper.load(element);}});});helper.log("registering observer done.");}else{helper.log("IntersectionObserver is not supported, skipping.");}},load:function(element){var helper=Altmetric.Helpers;if(element.classList.contains("metrics-badge")&&"_altmetric"in window){_altmetric.embed_init(element);}else{var includeZero=element.closest('.altmetric-score.true'),doi=element.dataset['doi'];$.ajax({url:'https://api.altmetric.com/v1/doi/'+doi+'?key='+Altmetric.Settings.key+'&callback=?',dataType:'jsonp',crossDomain:true,success:function(data){var score=data.score;score>0?prepend(Intl.NumberFormat().format(Math.ceil(score))):includeZero&&prepend();helper.log("loading altmetric score for "+doi+" is done, score = "+score);},error:function(e){includeZero&&prepend();helper.log("loading altmetric score for "+doi+" failed, cause: "+e.status);}});}
helper.registerListeners(element);function prepend(count){var holder=element.querySelector('.metrics-score');holder.style.visibility="visible";holder.innerText=(count||0);}},init:function(){var settings=Altmetric.Settings,helper=Altmetric.Helpers;if(!settings.registered){settings.registered=true;setTimeout(function(){helper.log("registering Altmetric logic");helper.registerObserver();document.querySelectorAll(".altmetric-score .value").forEach(function(element){settings.observer?settings.observer.observe(element):helper.load(element)});helper.log("init is done!");})}else{helper.log("registering Altmetric logic is already done.");}},registerListeners:function(element){if(element){var helper=Altmetric.Helpers;helper.log("registering altmetric listeners");element.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();var scoreLink=e.target.getAttribute('href')||element.querySelector('.altmetric-embed a').getAttribute('href'),badgeBehaviour=element.getAttribute('data-score-behaviour');if(badgeBehaviour==='linkToPopup')
helper.initAltmetricPopup(scoreLink);else if(badgeBehaviour==='linkToNewTab')
window.open(scoreLink,'_blank');})}},initAltmetricPopup:function(href){new Modal({content:"<div data-modal-name='altmetric' class='altmetricsPopup'><iframe src='"+href+"' class='altmetrics-frame'></iframe></div>",restrictFocus:true,maxWidth:1050,minWidth:650}).open();},log:function(message){console.debug("Altmetric:: "+message);}}}
$(document).on('altmetric:show',function(e){var target=e.target;var score=Object.values(_altmetric.badges[target.dataset['doi'].toLowerCase()])[0].score||0;target.setAttribute("data-score",score);var scoreElm=target.parentElement.querySelector(".score .metrics-score");if(scoreElm){scoreElm.innerText=score;}});$(document).on('altmetric:hide',function(e){var ele=e.target.parentElement.querySelector('.altmetric-no-score');if(ele){ele.show();}});$(Altmetric.Helpers.init);tandf.Altmetric=Altmetric;})(tandf);

